# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7170c0b28370ef6a36081846cd65e5d024bc64d45094d8e9caa8c31d21e8db095ea542e6dd008f00bc57cf32b782e493bca6ebb2d0b1d3730b1eee9be4416a30

test:
  secret_key_base: 98ebb498202ad94e63b26aad8970febee127bce8325615816c3e4d2a47acae7df48c79133ed8fff31ebab4ec9660f7508f082a2b1557d0e66cd1dcdedb1929d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
